version: '3.8'
services:
  mssql_db:
    container_name: mssql_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}


volumes:
  mssql_data:
